import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';

@Component({
  selector: 'app-equipment-efficiency-list-view',
  templateUrl: './equipment-efficiency-list-view.component.html',
  styleUrls: ['./equipment-efficiency-list-view.component.scss'],
})
export class EquipmentEfficiencyListViewComponent implements AfterViewInit {
  displayedColumns: string[] = [
    'equipment',
    'jobInfo',
    'OEE',
    'plannedCompletion',
    'estimatedCompletion',
    'production',
    'previousShiftAvailability',
    'currentShiftAvailability',
    'performance',
    'quality',
    'edit'
  ];
  dataSource = new MatTableDataSource<PeriodicElement>(ELEMENT_DATA);

  @ViewChild(MatPaginator) paginator!: MatPaginator;

  ngAfterViewInit() {
    this.dataSource.paginator = this.paginator;
  }
}

export interface PeriodicElement {
  equipment: string;
  jobInfo: string;
  OEE: number;
  plannedCompletion: number;
  estimatedCompletion: number;
  production: number;
  previousShiftAvailability: number;
  currentShiftAvailability: number;
  performance: number;
  quality: number;
}

const ELEMENT_DATA: PeriodicElement[] = [
  {
    equipment: '../../../assets/working.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/power-off.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/status.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/working.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/power-off.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/status.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/working.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/power-off.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/status.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/working.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/power-off.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/power-off.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/status.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/working.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/power-off.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/power-off.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/status.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/working.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/power-off.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  {
    equipment: '../../../assets/status.png',
    jobInfo: 'Hydrogen',
    OEE: 1.0079,
    plannedCompletion: 1,
    estimatedCompletion: 2,
    production: 3,
    previousShiftAvailability: 4,
    currentShiftAvailability: 4,
    performance: 4,
    quality: 5,
  },
  
];
